USE nerepdb;

CREATE TABLE `ACCESSNAME` (
  `ID` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `STARTTIME` time DEFAULT NULL,
  `ENDTIME` time DEFAULT NULL,
  `DOW` set('SUNDAY','MONDAY','TUESDAY','WEDNESDAY','THURSDAY','FRIDAY','SATURDAY') DEFAULT NULL,
  `ALLOWIP` varchar(15) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=latin1;


insert into `ACCESSNAME`(`ID`,`STARTTIME`,`ENDTIME`,`DOW`,`ALLOWIP`) values (1,'00:00:00','23:59:59','SUNDAY,MONDAY,TUESDAY,WEDNESDAY','%');
insert into `ACCESSNAME`(`ID`,`STARTTIME`,`ENDTIME`,`DOW`,`ALLOWIP`) values (2,'00:00:00','23:59:59','THURSDAY,FRIDAY,SATURDAY','%');
