USE nerepdb;

CREATE TABLE `ACCESSGROUP` (
  `ID` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `ACCESSGROUP_ID` int(10) unsigned NOT NULL,
  `ACCESSNAME_ID` int(10) unsigned NOT NULL,
  PRIMARY KEY (`ID`),
  KEY `fk_AG1_ACCESSGROUP` (`ACCESSGROUP_ID`),
  KEY `fk_AG1_ACCESSNAME` (`ACCESSNAME_ID`),
  CONSTRAINT `fk_AGR_ACCESSNAME` FOREIGN KEY (`ACCESSNAME_ID`) REFERENCES `ACCESSNAME` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB AUTO_INCREMENT=9 DEFAULT CHARSET=latin1;


insert into `ACCESSGROUP`(`ID`,`ACCESSGROUP_ID`,`ACCESSNAME_ID`) values (1,1,1);
insert into `ACCESSGROUP`(`ID`,`ACCESSGROUP_ID`,`ACCESSNAME_ID`) values (2,1,2);
insert into `ACCESSGROUP`(`ID`,`ACCESSGROUP_ID`,`ACCESSNAME_ID`) values (3,2,1);
insert into `ACCESSGROUP`(`ID`,`ACCESSGROUP_ID`,`ACCESSNAME_ID`) values (4,2,2);
insert into `ACCESSGROUP`(`ID`,`ACCESSGROUP_ID`,`ACCESSNAME_ID`) values (5,3,1);
insert into `ACCESSGROUP`(`ID`,`ACCESSGROUP_ID`,`ACCESSNAME_ID`) values (6,3,2);
insert into `ACCESSGROUP`(`ID`,`ACCESSGROUP_ID`,`ACCESSNAME_ID`) values (7,4,1);
insert into `ACCESSGROUP`(`ID`,`ACCESSGROUP_ID`,`ACCESSNAME_ID`) values (8,4,2);
