USE nerepdb;

CREATE TABLE `ATTRIB_LIST` (
  `ID` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `ATTRIB_TYPE_ID` int(11) DEFAULT NULL,
  `NAME` varchar(128) DEFAULT NULL,
  `DESCRIPTION` int(11) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;


