USE nerepdb;

CREATE TABLE `GROUPAUTHORIZE` (
  `ID` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `GROUPNAME_ID` int(11) unsigned NOT NULL,
  `PAGENAME_ID` int(11) NOT NULL DEFAULT '0',
  `ACCESSGROUP_ID` int(11) unsigned DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `fk_GAU_PAGENAME` (`PAGENAME_ID`),
  KEY `fk_GAU_GROUPNAME` (`GROUPNAME_ID`),
  KEY `fk_GAU_ACCESSNAME` (`ACCESSGROUP_ID`),
  CONSTRAINT `fk_GAU_ACCESSNAME` FOREIGN KEY (`ACCESSGROUP_ID`) REFERENCES `ACCESSGROUP` (`ACCESSGROUP_ID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_GAU_GROUPNAME` FOREIGN KEY (`GROUPNAME_ID`) REFERENCES `GROUPNAME` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `FK_GROUPAUTHORIZE_ACCESSGROUP_ID` FOREIGN KEY (`ACCESSGROUP_ID`) REFERENCES `ACCESSGROUP` (`ACCESSGROUP_ID`),
  CONSTRAINT `FK_GROUPAUTHORIZE_GROUPNAME_ID` FOREIGN KEY (`GROUPNAME_ID`) REFERENCES `GROUPNAME` (`ID`),
  CONSTRAINT `FK_GROUPAUTHORIZE_PAGENAME_ID` FOREIGN KEY (`PAGENAME_ID`) REFERENCES `PAGENAME` (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=28 DEFAULT CHARSET=latin1;


insert into `GROUPAUTHORIZE`(`ID`,`GROUPNAME_ID`,`PAGENAME_ID`,`ACCESSGROUP_ID`) values (1,1,2,1);
insert into `GROUPAUTHORIZE`(`ID`,`GROUPNAME_ID`,`PAGENAME_ID`,`ACCESSGROUP_ID`) values (2,1,3,1);
insert into `GROUPAUTHORIZE`(`ID`,`GROUPNAME_ID`,`PAGENAME_ID`,`ACCESSGROUP_ID`) values (5,1,4,1);
insert into `GROUPAUTHORIZE`(`ID`,`GROUPNAME_ID`,`PAGENAME_ID`,`ACCESSGROUP_ID`) values (6,1,5,1);
insert into `GROUPAUTHORIZE`(`ID`,`GROUPNAME_ID`,`PAGENAME_ID`,`ACCESSGROUP_ID`) values (7,1,6,1);
insert into `GROUPAUTHORIZE`(`ID`,`GROUPNAME_ID`,`PAGENAME_ID`,`ACCESSGROUP_ID`) values (8,1,7,1);
insert into `GROUPAUTHORIZE`(`ID`,`GROUPNAME_ID`,`PAGENAME_ID`,`ACCESSGROUP_ID`) values (9,1,7,1);
insert into `GROUPAUTHORIZE`(`ID`,`GROUPNAME_ID`,`PAGENAME_ID`,`ACCESSGROUP_ID`) values (10,1,8,1);
insert into `GROUPAUTHORIZE`(`ID`,`GROUPNAME_ID`,`PAGENAME_ID`,`ACCESSGROUP_ID`) values (11,1,9,1);
insert into `GROUPAUTHORIZE`(`ID`,`GROUPNAME_ID`,`PAGENAME_ID`,`ACCESSGROUP_ID`) values (12,1,10,1);
insert into `GROUPAUTHORIZE`(`ID`,`GROUPNAME_ID`,`PAGENAME_ID`,`ACCESSGROUP_ID`) values (13,1,11,1);
insert into `GROUPAUTHORIZE`(`ID`,`GROUPNAME_ID`,`PAGENAME_ID`,`ACCESSGROUP_ID`) values (14,1,12,1);
insert into `GROUPAUTHORIZE`(`ID`,`GROUPNAME_ID`,`PAGENAME_ID`,`ACCESSGROUP_ID`) values (15,2,2,2);
insert into `GROUPAUTHORIZE`(`ID`,`GROUPNAME_ID`,`PAGENAME_ID`,`ACCESSGROUP_ID`) values (16,2,3,2);
insert into `GROUPAUTHORIZE`(`ID`,`GROUPNAME_ID`,`PAGENAME_ID`,`ACCESSGROUP_ID`) values (17,2,4,2);
insert into `GROUPAUTHORIZE`(`ID`,`GROUPNAME_ID`,`PAGENAME_ID`,`ACCESSGROUP_ID`) values (18,2,5,2);
insert into `GROUPAUTHORIZE`(`ID`,`GROUPNAME_ID`,`PAGENAME_ID`,`ACCESSGROUP_ID`) values (19,2,7,2);
insert into `GROUPAUTHORIZE`(`ID`,`GROUPNAME_ID`,`PAGENAME_ID`,`ACCESSGROUP_ID`) values (20,3,2,3);
insert into `GROUPAUTHORIZE`(`ID`,`GROUPNAME_ID`,`PAGENAME_ID`,`ACCESSGROUP_ID`) values (21,3,3,3);
insert into `GROUPAUTHORIZE`(`ID`,`GROUPNAME_ID`,`PAGENAME_ID`,`ACCESSGROUP_ID`) values (22,3,4,3);
insert into `GROUPAUTHORIZE`(`ID`,`GROUPNAME_ID`,`PAGENAME_ID`,`ACCESSGROUP_ID`) values (23,3,6,3);
insert into `GROUPAUTHORIZE`(`ID`,`GROUPNAME_ID`,`PAGENAME_ID`,`ACCESSGROUP_ID`) values (24,3,8,3);
insert into `GROUPAUTHORIZE`(`ID`,`GROUPNAME_ID`,`PAGENAME_ID`,`ACCESSGROUP_ID`) values (25,4,9,4);
insert into `GROUPAUTHORIZE`(`ID`,`GROUPNAME_ID`,`PAGENAME_ID`,`ACCESSGROUP_ID`) values (26,4,10,4);
insert into `GROUPAUTHORIZE`(`ID`,`GROUPNAME_ID`,`PAGENAME_ID`,`ACCESSGROUP_ID`) values (27,1,13,1);
