USE nerepdb;

CREATE TABLE `GROUPNAME` (
  `ID` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `NAME` varchar(32) DEFAULT NULL,
  `COMMENT` varchar(256) DEFAULT NULL,
  `ACCESSGROUP_ID` int(11) unsigned DEFAULT NULL,
  `PLATFORM_ID` int(10) unsigned DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `fk_GN_ACCESSGROUP` (`ACCESSGROUP_ID`),
  KEY `fk_GN_PLATFORM` (`PLATFORM_ID`),
  CONSTRAINT `fk_GN_ACCESSGROUP` FOREIGN KEY (`ACCESSGROUP_ID`) REFERENCES `ACCESSGROUP` (`ACCESSGROUP_ID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_GN_PLATFORM` FOREIGN KEY (`PLATFORM_ID`) REFERENCES `PLATFORM` (`ID`) ON DELETE SET NULL ON UPDATE SET NULL,
  CONSTRAINT `FK_GROUPNAME_ACCESSGROUP_ID` FOREIGN KEY (`ACCESSGROUP_ID`) REFERENCES `ACCESSGROUP` (`ACCESSGROUP_ID`),
  CONSTRAINT `FK_GROUPNAME_PLATFORM_ID` FOREIGN KEY (`PLATFORM_ID`) REFERENCES `PLATFORM` (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=5 DEFAULT CHARSET=latin1;


insert into `GROUPNAME`(`ID`,`NAME`,`COMMENT`,`ACCESSGROUP_ID`,`PLATFORM_ID`) values (1,'Administrators','Administrators Group',1,1);
insert into `GROUPNAME`(`ID`,`NAME`,`COMMENT`,`ACCESSGROUP_ID`,`PLATFORM_ID`) values (2,'Online','Online Report Only',1,1);
insert into `GROUPNAME`(`ID`,`NAME`,`COMMENT`,`ACCESSGROUP_ID`,`PLATFORM_ID`) values (3,'WiFi','WiFi Report Only',1,1);
insert into `GROUPNAME`(`ID`,`NAME`,`COMMENT`,`ACCESSGROUP_ID`,`PLATFORM_ID`) values (4,'Authen','Authen Log Only',1,1);
