USE nerepdb;

CREATE TABLE `NE_CHNG_LOG` (
  `ID` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `PREV_DATE` datetime NOT NULL,
  `CURR_DATE` datetime NOT NULL,
  `IP_ADDR` varchar(32) NOT NULL,
  `CURR_INDEX_HASH` varchar(32) DEFAULT NULL,
  `PREV_INDEX_HASH` varchar(32) DEFAULT NULL,
  `EVENT_TYPE` set('ADD','MODIFY','REMOVE') DEFAULT NULL,
  `EVENT_NAME` varchar(256) DEFAULT NULL,
  `COMMENT` varchar(256) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;


