USE nerepdb;

CREATE TABLE `USERNAME` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `NAME` varchar(64) DEFAULT NULL,
  `FULL_NAME` varchar(64) DEFAULT NULL,
  `COMMENT` varchar(256) DEFAULT NULL,
  `PASSWORD` varchar(64) DEFAULT NULL,
  `EMAIL` varchar(64) DEFAULT NULL,
  `GROUPNAME_ID` int(11) unsigned DEFAULT NULL,
  `ACCESSGROUP_ID` int(11) unsigned DEFAULT NULL,
  `LAST_LOGIN_DATE` datetime DEFAULT NULL,
  `LAST_LOGIN_IP` varchar(32) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `fk_UN_GROUPNAME` (`GROUPNAME_ID`),
  KEY `fk_UN_ACCESSGROUP` (`ACCESSGROUP_ID`),
  CONSTRAINT `fk_UN_ACCESSGROUP` FOREIGN KEY (`ACCESSGROUP_ID`) REFERENCES `ACCESSGROUP` (`ACCESSGROUP_ID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_UN_GROUPNAME` FOREIGN KEY (`GROUPNAME_ID`) REFERENCES `GROUPNAME` (`ID`),
  CONSTRAINT `FK_USERNAME_ACCESSGROUP_ID` FOREIGN KEY (`ACCESSGROUP_ID`) REFERENCES `ACCESSGROUP` (`ACCESSGROUP_ID`),
  CONSTRAINT `FK_USERNAME_GROUPNAME_ID` FOREIGN KEY (`GROUPNAME_ID`) REFERENCES `GROUPNAME` (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=5 DEFAULT CHARSET=latin1;


insert into `USERNAME`(`ID`,`NAME`,`FULL_NAME`,`COMMENT`,`PASSWORD`,`EMAIL`,`GROUPNAME_ID`,`ACCESSGROUP_ID`,`LAST_LOGIN_DATE`,`LAST_LOGIN_IP`) values (1,'admin','Admin','Administrator','21232f297a57a5a743894a0e4a801fc3',null,1,null,null,null);
insert into `USERNAME`(`ID`,`NAME`,`FULL_NAME`,`COMMENT`,`PASSWORD`,`EMAIL`,`GROUPNAME_ID`,`ACCESSGROUP_ID`,`LAST_LOGIN_DATE`,`LAST_LOGIN_IP`) values (2,'online','Online Report','Online Report Only',null,null,2,null,null,null);
insert into `USERNAME`(`ID`,`NAME`,`FULL_NAME`,`COMMENT`,`PASSWORD`,`EMAIL`,`GROUPNAME_ID`,`ACCESSGROUP_ID`,`LAST_LOGIN_DATE`,`LAST_LOGIN_IP`) values (3,'wifi','WiFi Report','WiFi Report Only',null,null,3,null,null,null);
insert into `USERNAME`(`ID`,`NAME`,`FULL_NAME`,`COMMENT`,`PASSWORD`,`EMAIL`,`GROUPNAME_ID`,`ACCESSGROUP_ID`,`LAST_LOGIN_DATE`,`LAST_LOGIN_IP`) values (4,'authen','Authen Log','Authen Log Only',null,null,4,null,null,null);
